[tool.poetry]
name = "cdktf-python-pdm"
version = "1.0.0"
description = ""
authors = []
dependencies = [
    "cdktf>=0.12.2",
]
requires-python = ">=3.9"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]