name: tag
on:
  push:
    branches:
      - main

jobs:
  tag_commit:
    name: Tag a commit to main branch with version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get version number
        run: |
          cat tf.properties >> "$GITHUB_ENV"
      - name: Tag commit with version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ env.version }}


